{% set name = "spacy-legacy" %}
{% set modulename = "spacy_legacy" %}
{% set version = "3.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b37d6e0c9b6e1d7ca1cf5bc7152ab64a4c4671f59c85adaf7a3fcb870357a774

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - {{ modulename }}
  requires:
    - pytest
    - wandb
    - spacy >=3.1.0,<3.3.0
  commands:
    - python -m pytest --tb=native --pyargs {{ modulename }}


about:
  home: https://github.com/explosion/spacy-legacy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Legacy functions and architectures for backwards compatibility
  description: |
    This package includes outdated registered functions for spaCy v3.x, for
    example model architectures, pipeline components and utilities.
  doc_url: https://github.com/explosion/spacy-legacy
  dev_url: https://github.com/explosion/spacy-legacy

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
